Chained Exceptions

PEP 3134
https://www.python.org/dev/peps/pep-3134/

- If an exception occurs when handling a different exception, the originating exception is lost
- Provides a way to see the historical chain of exceptions